name: Develop

on:
  pull_request:
    branches:
      - develop
      - feature/**
  push:
    branches:
      - develop
      - feature/**

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 18.x
          - 20.x

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install apt packages for headless-gl
        run: sudo apt update && sudo apt install libxi-dev xvfb libgl1-mesa-dev

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          run_install: false

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint-check

      - name: Test
        run: xvfb-run --auto-servernum pnpm test-coverage

      - name: Coverage
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: chmod +x minify.sh && yarn run semantic-release --dry-run
