name: Main

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 12.x
          - 14.x
          - 16.x

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install apt packages for headless-gl
        run: sudo apt update && sudo apt install libxi-dev xvfb libgl1-mesa-dev
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - name: Cache node_modules
        id: node_modules_cache_id
        uses: actions/cache@v2　
        with:
          path: node_modules
          key: node-v${{ matrix.node-version }}-deps-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
      - name: Export environment variables
        run: export TERM=xterm
      - name: Install dependencies
        if: steps.node_modules_cache_id.outputs.cache-hit != 'true'
        run: yarn --check-files --frozen-lockfile --non-interactive
      - name: Run eslint
        run: yarn lint
      - name: Run test
        run: xvfb-run --auto-servernum yarn test:ci
      - name: Generating coverage badges
        uses: jpb06/jest-badges-action@latest
        with:
          branches: main,develop
